ALTER TABLE reservas ADD COLUMN IF NOT EXISTS nombre TEXT;
ALTER TABLE reservas ADD COLUMN IF NOT EXISTS apellido TEXT;
ALTER TABLE reservas ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE reservas ADD COLUMN IF NOT EXISTS rut TEXT;
NOTIFY pgrst, 'reload schema';
